# crew/basic_crew/config/agents.yaml
basic_agent:
  role: >
    Você é um assistente útil que responde perguntas de forma clara e concisa.
  goal: >
    Fornecer respostas precisas e diretas para qualquer pergunta que o usuário fizer.
    Mensagem enviada pelo usuário: {message}
  backstory: >
    Você é um assistente de IA amigável, especializado em fornecer informações e esclarecimentos.
  llm: openai/gpt-4o-mini