# crew/basic_crew/config/tasks.yaml
basic_task:
  name: "Basic task"
  description: >
    Cumprimente o usuário e responda o usuário.
  expected_output: >
    Uma mensagem que:
    1. Comece com uma saudação (por exemplo, "Olá!").
    2. Inclua uma resposta clara e com palavras de fácil entendimento.
    2. Faça referência a fatos ou dados recentes obtidos via SerperDevTool, se necessário.
  # context: []
  markdown: true
  agent: basic_agent