# fly.toml app configuration file generated for crewai-api on 2025-05-31T18:55:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crewai-api'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
