# crew/dev_crew/config/tasks.yaml
leader_task:
  name: "leader_task"
  description: >
    Analisar a solicitação do usuário para uma nova aplicação CrewAI sobre {message}.
    Você deve utilizar seu conhecimento aprofundado sobre o framework CrewAI,
    incluindo suas funcionalidades de 'Knowledge', 'Memory', 'Agents', 'Tasks', e 'Tools',
    para desenvolver um plano de projeto detalhado e estratégico para a Meta-Equipe.
    Se necessário, utilize suas ferramentas de pesquisa web para obter informações adicionais
    ou contexto específico sobre o {message} da aplicação solicitada.

    O plano de projeto deve:
    1. Identificar claramente as fases do projeto de desenvolvimento da nova aplicação CrewAI.
    2. Atribuir responsabilidades conceituais aos diferentes especialistas que comporiam a Meta-Equipe.
    3. Definir os entregáveis esperados para cada fase e os critérios de aceitação.
    4. Estabelecer pontos de verificação e revisão para garantir o alinhamento e a qualidade.
    5. Delinear como os princípios e as melhores práticas do CrewAI serão aplicados em cada etapa.

    O plano deve ser um roteiro completo, acionável e bem fundamentado nos conceitos do CrewAI.
  expected_output: >
    Um documento de 'Plano de Projeto Estratégico' em formato Markdown.
    Este plano deve detalhar:
    - Sumário da Solicitação do Usuário e Objetivos da Aplicação sobre {message}.
    - Fases do Projeto (ex: Concepção, Design dos Agentes, Desenvolvimento, Testes, Documentação).
    - Matriz de Responsabilidades (descrição dos papéis dos agentes especialistas na Meta-Equipe e suas principais contribuições).
    - Cronograma Estimado (uma visão geral das durações esperadas para as fases).
    - Estratégia de Aplicação dos Conceitos CrewAI (como 'Knowledge', 'Memory', 'Tools', 'Reasoning', 'Planning' serão utilizados na aplicação proposta).
    - Pontos de Controle e Métricas de Sucesso.
  agent: leader
  markdown: True
  output_file: output/plano_de_projeto_estrategico.md
